### PR TITLE
feat(customElement) add property change handlers

### LINKED ISSUE #5: Updating bound properties does not update icon
**I'm submitting a bug report**

* **Library Version:**
0.1.0

* **Browser:**
all
**Current behavior:**

Using the custom element with attributes bound to the viewmodel does not update the icon when the attributes are changed. For example:

```
<font-awesome-icon icon="coffee" spin.bind="doTheSpin"></font-awesome-icon>
```

The icon does not spin/stop-spinning depending on `doTheSpin`. It only reads the value of `doTheSpin` during activation of the view.

**What is the expected behavior?**
That the properties of the icon can be updated during the lifetime of the view model

**What is the motivation / use case for changing the behavior?**
I want to avoid having to `if.bind` the icons depending on the properties

### PR DESCRIPTION
**Pull request by rmja**
Fixes #5.

I am not completely happy with `replaceIcon()`. It seems a little rude.

### CODE REVIEW

**Comment by jmzagorski** [comment]
@rmja   Thank you for the PR. I was actually finishing my branch up as well so we can compare the two pull requests. Writing the unit tests was actually holding me up. I will be submitting that in the next hour or so.

I do like how you introduced type aliases!

**Comment by jmzagorski** [comment]
@rmja  I was finally able to get my tests working and submitted the work i started when you submitted the initial issue (PR #8). I took a different approach and added two change handlers `propertyChanged` and `iconChanged` and moved some of the logic from `attached` to a private `renderIcon` function. I thought about adding different change handlers for particular bindables so that those methods can handle their updates instead of having the  one `classObj`, but it did not flow as well and added a lot of extra code without too much benefit that I could see.

**Comment by jmzagorski** [comment]
> I thought about adding different change handlers for particular bindables so that those methods can handle their updates instead of having the one `classObj`

I hope you did not change your code because of what I said. I should have been more clear and said it did not flow in the changes i did in my PR. Sorry about that if that was the case.

I am not against this, but it does add a significant amount of code to maintain in the switch statement (and when i see a switch statement I always feel like its should be refactored out to a factory service) 

Also, it has some duplication with the class names in the switch statement and the `classObj` variable (though I am sure that can be refactored). 

Based on the two PRs right now, I'd prefer to recompile the icon when any property changes unless there is a cleaner way to update the classes on the svg. (side note: We do have access to the `view`, so there might not be a need to run `querySelector`, but i have not tested that). I ran my PR in the sample app and I do not see any performance issues right now when changing 4 bindable properties one after, which took anywhere from 1 to less than 1 millisecond)

Let me know if you are okay with that unless you feel strongly about changing the class list.

**Comment by rmja** [comment]
It is fine with me, I am just prototyping. I was actually not aware that a propertyChanged callback existed in aurelia.

We just need to be 100pct. certain that there is no memory leak when the icon is swapped.

**Comment by jmzagorski** [comment]
Do you have a way to test if there is a memory leak?  

When you said that I just realized in my `iconChanged` method in the PR did not call detached to clean up the older svg.

**Comment by rmja** [comment]
You can see it in the memory tab in chrome. I can have a look at it tomorrow if you want.

**Comment by jmzagorski** [comment]
It might be good if you look to help me understand which piece of data you are viewing in your snapshots. I want to leave my PR branch as is for now (without calling detach on `iconChanged`) since that has a greater chance of having a memory leak, and I can submit my fix to that branch later. 

I plan on moving the https://github.com/jmzagorski/aurelia-fontawesome-samples repository to a examples subfolder so it is easier to run, but I just pointed that sample app to the PR branch and added this to the app.ts:

```typescript
export class App {
  message = 'Aurelia FontAwesome 5 Samples';
  icon = 'circle';

  activate() {
    setInterval(() => {
      this.icon = (this.icon == 'circle' ? 'coffee' : 'circle');
    }, 4000);
  }
}
```

The icon should change from a circle to coffee every 4 seconds, recompiling the icon. Thank you.

**Comment by jmzagorski** [comment]
Thank you for the contribution and really the conversation on this subject. It helped me dig into the custom element a little more to discover we did not need all the services from aurelia and rather we could use the innerhtml binding. If you have any concerns please let me know.

**Pull request closed without merging**
