### PR TITLE
Add support for stacking icons

### PR DESCRIPTION
**Pull request by rmja**
... as per https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons

### CODE REVIEW

**Comment by jmzagorski** [comment]
Thank you for this PR! Were you able to test this out within a web application? I repacked the new code with npm and ran it locally in https://github.com/jmzagorski/aurelia-fontawesome-samples and it did not stack. I added a row to the table to demonstrate stacking and the two icons appeared next to each other instead of stacking. Below is the code I added to the sample repository:

```html
      <tr>
        <td>Stacking</td>
        <td>
          <span class="fa-stack fa-4x">
            <font-awesome-icon icon="square" stack="2x"></font-awesome-icon>
            <font-awesome-icon icon="home" stack="1x"></font-awesome-icon>
          </span>
        </td>
      </tr>
```

to run locally i added this to my package.json in the samples library
```json
    "aurelia-fontawesome": "file:../aurelia-fontawesome/aurelia-fontawesome-0.1.0.tgz",
```

Let me know if i am doing something incorrect.

**Comment by rmja** [comment]
Yes, I am using it. The steps I did are here: https://github.com/jmzagorski/aurelia-fontawesome-samples/commit/a529a71de4343e02134ac45d85fdc1f4267561f9

**Comment by jmzagorski** [comment]
Thanks! I will check it over the weekend and merge unless I have other follow up questions.

**Comment by jmzagorski** [comment]
This looks good from your example. The `"aurelia-fontawesome": "file:../aurelia-fontawesome/aurelia-fontawesome-0.1.0.tgz",` in the package.json does not seem to work, but that does not surprise me as I had problems using local packages before.

Would you mind to rewrite your commit message to use use [standard version](https://github.com/conventional-changelog/standard-version) convention. E.g `feat(icon): Add fa-stack support`. Or i can squash merge this PR. Whichever you prefer. Thanks again for the help

**Comment by rmja** [comment]
there you go

**Pull request merged**
