### PR TITLE
fix(customElement) fix regression caused by #5

### PR DESCRIPTION
**Pull request by rmja**

### CODE REVIEW

**Comment by jmzagorski** [comment]
I thought this was working? I tested `<i>` out on IE and firefox (though I can't remember if i did chrome or edge)

Also, please do not forget the colon (:) after the commit subject<type> (full commit message below). Sorry to be a stickler on that. I use https://github.com/semantic-release/semantic-release to parse the commit messages and create the change log, and I am not sure if it would parse it incorreclty without the colon.

```
<type>[optional scope]: <description>

[optional body]

[optional footer]
```

**Comment by rmja** [comment]
Ahh...
It works, but the component is unable to later swap out the icon. It results in two icons being rendered as by https://github.com/jmzagorski/aurelia-fontawesome/pull/8#issuecomment-463522609

**Comment by jmzagorski** [comment]
With this fix, it will not work in IE11 though right?

**Comment by rmja** [comment]
It works in IE. The aurelia view compiler handles IE compatability internally when the view is passed in as a string.

**Comment by jmzagorski** [comment]
I am going to wait to include this change in the property changed pull request since that is where you see the issue. Part of the reason for this is we cannot write a test that checks for duplicated icons when the icon changes (as was evident on my PR branch).

**Comment by jmzagorski** [comment]
Again, i really appreciate your help to make this library better.  Since #8 was merged this is not needed anymore since the library is not compiling the template

**Pull request closed without merging**
